### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by mynameismon** [sidhant-sriv/12thPracticals-term2#1]
https://github.com/sidhant-sriv/12thPracticals-term2/blob/242c79679862a03e3e0c51993fe754785e3886ab/question_10.py#L20

Can be reduced to 

```py
 mycursor.execute("SELECT * FROM Items ORDER BY CostPerItem DESC LIMIT 1") 
 ```

**Comment by sidhant-sriv** [comment]
Bro just make the change then raise a PR . Also check the Note in README.md
