### ISSUE TITLE
<connectionObject>.close() and <connectionObject>.commit() in all SQL programs.

### ISSUE THREAD

**Issue by sandhyacv** [sidhant-sriv/12thPracticals-term2#11]
The first may be pointless but the changes will not be permanent i.e. reflected in the database without commit().

**Comment by sidhant-sriv** [comment]
@sandhyacv Do we need permanent changes? The goal of the sql queries was to create an environment to test the queries in the code. 
But if you think commits should be done then talk to @mynameismon about it or just make the changes yourself.
